INSERT INTO CINEMA (ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Major.15','Tarragona','Oscars','43100');

INSERT INTO CINEMA (ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Major.25','Tarragona','JCS','43100');

INSERT INTO CINEMA (ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Major.35','Tarragona','Yelmus','43100');