INSERT INTO CINEMA (ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Major.15','Tarragona','Oscars','43100');

INSERT INTO CINEMA (ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Major.25','Tarragona','JCS','43100');

INSERT INTO CINEMA (ADDRESS,CITY,CINEMA_NAME,POSTAL_CODE) VALUES
('Major.35','Tarragona','Yelmus','43100');

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES 
('Sala 1',120,1);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES 
('Sala 2',120,1);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES 
('Sala 3',120,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES 
('Sala 1',120,2);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES 
('Sala 2',120,2);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES 
('Sala 3',120,2);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES 
('Sala 1',120,3);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES 
('Sala 2',120,3);
INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES 
('Sala 3',120,3);